### ISSUE TITLE
estado_oportunidad

### ISSUE THREAD

**Issue by YeiMonsalve** [YeiMonsalve/EAFIT-Project#7]
# **Historia de Usuario: Tabla de Estado de Oportunidades**

Como desarrollador, necesito crear una tabla para gestionar el estado de las oportunidades, de forma que se puedan almacenar y consultar los distintos estados asociados a cada oportunidad.

### 1. Crear la tabla **estado_oportunidad** en la base de datos MySQL desde Java usando JPA.

**La tabla debe incluir los siguientes campos:**

- id INT AUTO_INCREMENT PRIMARY KEY
- estado VARCHAR(100)

### 2. Implementar las operaciones CRUD para la tabla **estado_oportunidad**:

- Crear un nuevo estado de oportunidad.
- Leer (listar) todos los estados de oportunidad.
- Actualizar un estado de oportunidad existente.
- Eliminar un estado de oportunidad.

### 3. Crear los DTOs (Data Transfer Objects) necesarios para **estado_oportunidad**:

- **NoIdDTO (Para llaves foráneas)**: Este DTO solo traerá el `id` del estado y será utilizado en tablas relacionadas que necesiten una referencia al estado mediante una llave foránea.
- **JustIdDTO (Para creación y actualización)**: Este DTO traerá todos los campos del estado excepto el `id`, ya que el `id` es autogenerado. Este DTO se usará en las operaciones de creación y actualización de un estado de oportunidad.

### 4. Documentación con Swagger:

Incluir la documentación de todos los endpoints disponibles para las operaciones CRUD de la tabla **estado_oportunidad**.

### 5. Testing de la API con Postman:

- Probar los endpoints CRUD de **estado_oportunidad** utilizando Postman.
- Incluir capturas de pantalla de las pruebas realizadas.

## **Puntos de Historia de Usuario**

**Complejidad:** 8 puntos

- 2 puntos para la creación de la tabla en la base de datos.
- 2 puntos para la implementación de la lógica CRUD.
- 1 punto para la creación de los endpoints REST.
- 2 puntos para la creación de los dos DTOs y su integración en el código.
- 1 punto para el manejo de errores y validaciones.

## **Notas**

- Validar que se utilicen correctamente los DTOs en los endpoints.
- Se debe incluir un manejo adecuado de errores, como la validación de solicitudes inválidas y el manejo de estados no encontrados.
- Las pruebas unitarias y de integración deben asegurarse de que todas las funcionalidades se comporten como se espera.
- La historia de usuario se debe trabajar en la siguiente ruta:  
![Image](https://github.com/user-attachments/assets/9aca7c4b-080a-4d7b-8d7a-9c5092ffbaf2)

**Comment by Teo1188** [comment]
Se realizan los siguientes puntos sin ningún inconveniente:

1. Crear la tabla estado_oportunidad en la base de datos MySQL desde Java usando JPA.
2. Implementar las operaciones CRUD para la tabla estado_oportunidad
3. Crear los DTOs (Data Transfer Objects) necesarios para estado_oportunidad
4. Documentación con Swagger
5. Testing de la API con Postman:
Se prueban los endpoints CRUD de estado_oportunidad utilizando Postman.
se envian las capturas de pantalla de las pruebas realizadas al scrumMaster Yeson Monsalve.

![Image](https://github.com/user-attachments/assets/425ea982-d79d-4802-9b91-c2745472be2b)

![Image](https://github.com/user-attachments/assets/3061b55a-bbab-4f62-b329-088e216b1a76)

![Image](https://github.com/user-attachments/assets/584fbf38-f048-45be-8d0d-1395a46872f8)

![Image](https://github.com/user-attachments/assets/98dc57d8-4686-44d0-806d-8a0eb6878a95)

![Image](https://github.com/user-attachments/assets/cc97cd6e-1611-4d5f-a9c1-1c7b4c4ae075)
